Fix conditional typo and stop post commands tasks, if there's an error

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -40,8 +40,12 @@ fi
 ## POST SCRIPT TASKS ##
 #######################
 
-# Execute zsh
-echo "[SETUP_INFO] : Executing zsh on current user..."
-exec zsh
+if [[ $? = 0 ]]; then
+    # Execute zsh
+    echo "[SETUP_INFO] : Executing zsh on current user..."
+    exec zsh
 
-echo "SETUP FINISHED"
+    echo "SETUP FINISHED"
+else
+    echo "[SETUP_ERROR] : Script was interrupted by an unexpected error."
+fi
